name: "Testapp deploy CI/CD"

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  deploy:
    name: Build and Deploy testapp
    outputs:
      image_tag: ${{ env.TAG }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Yandex Cloud Container Registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YCAUTHKEYJSON }}

      - name: Get tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "Current tag: $TAG"
      - name: Build, and push image to Yandex Cloud Container Registry
        if: github.event_name == 'push' && github.ref_type != 'tag'
        env:
          CR_REGISTRY: crpp9acq3pqq72ip67ni
          CR_REPOSITORY: myapp-test
          IMAGE_TAG: ${GITHUB_REF#refs/tags/}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY ./docker/
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        if: github.ref_type == 'tag' # ==
        env:
          CR_REGISTRY: crpp9acq3pqq72ip67ni
          CR_REPOSITORY: myapp-test
          IMAGE_TAG: ${GITHUB_REF#refs/tags/} 
        run: |
          TAG=${GITHUB_REF#refs/tags/} 
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$TAG ./docker/
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$TAG

      - name: Prepare deployment
        if: github.ref_type == 'tag' # ==
        env:
          IMAGE_TAG: ${GITHUB_REF#refs/tags/}
        run: |
          TAG=${GITHUB_REF#refs/tags/} 
          sudo sed "s/0.1/$TAG/" ./deploy/deployment.yml 
          sudo sed "s/first/$TAG/" ./deploy/deployment.yml

      - name: Deploy app
        if: github.ref_type == 'tag' # == 
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.CONFG_K8S }}
        with:
          args: apply -f ./deploy/ -n nsapptest --insecure-skip-tls-verify

      - name: Check deployment
        if: github.ref_type == 'tag' # ==
        run: |
         sudo cat ./deploy/deployment.yml 


      # - name: restart
      #   if: github.ref_type == 'tag' # == 
      #   uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG: ${{ secrets.CONFG_K8S }}
      #   with:
      #     args: rollout restart deployment/apptest -n nsapptest --insecure-skip-tls-verify

